#! /bin/sh
# Set the username and password for the web user.
if [ x${ELASTIC_PASSWORD} == x ]; then
    echo "Set the ELASTICSEARCH_PASS environment variable in the .env file";
    exit 1;
elif [ x${ELASTICSEARCH_RAPIDEZ_PASS} == x ]; then
    echo "Set the ELASTICSEARCH_RAPIDEZ_PASS environment variable in the .env file";
    exit 1;
fi;
echo "Setting passwords";
until curl -s -X POST "localhost:9200/_security/role/web?pretty" -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" -d'{"indices": [{"names": [ "rapidez_*" ],"privileges": ["read"]}]}' | grep "^{"; do sleep 10; done;
until curl -s -X POST "localhost:9200/_security/user/web?pretty" -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" -d'{"password" : "${ELASTICSEARCH_RAPIDEZ_PASS}","roles" : [ "web" ]}' | grep "^{"; do sleep 10; done;
echo "All done!";
