services:
  # Automatically route incoming requests based on their labels.
  # Remove this and the labels if you want to route the requests manually.
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    command: --providers.docker --providers.docker.exposedbydefault=false
    networks:
      - default
    ports:
      - "${TRAEFIK_PORT:-80}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
